[workspace]
resolver = "2"
members = ["canister", "server"]

[workspace.package]
name = "icda"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
candid = "0.10"

[workspace.dependencies.sha2]
version = "0.10.8"

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1"